const ACTIONS = {
    DEPLOY_FETCH_INIT: 'DEPLOY_FETCH_INIT',
    DEPLOY_FETCH_SUCCESS: 'DEPLOY_FETCH_SUCCESS',
    DEPLOY_FETCH_FAIL: 'DEPLOY_FETCH_FAIL',
    DEPLOY_INVALIDATE: 'TEMPLATE_INVALIDATE'
};
  
export default ACTIONS;