const ACTIONS = {
    TEMPLATE_FETCH_INIT: 'TEMPLATE_FETCH_INIT',
    TEMPLATE_FETCH_SUCCESS: 'TEMPLATE_FETCH_SUCCESS',
    TEMPLATE_FETCH_FAIL: 'TEMPLATE_FETCH_FAIL',
    TEMPLATE_INVALIDATE: 'TEMPLATE_INVALIDATE'
};
  
export default ACTIONS;